### ISSUE TITLE
can_parse_json and repair_json not working on this string

### ISSUE THREAD

**Issue by marklysze** [Qarj/fix-busted-json#6]
I believe the following is valid JSON, but `can_parse_json` returns `False` and `repair_json` throws an exception `Expected open brace`. Have I got it wrong?

JSON:
[{"name": "weather_forecast", "arguments":{"location": "New York"}},{"name": "currency_calculator", "arguments":{"base_amount": 123.45, "base_currency": "EUR", "quote_currency": "USD"}}]

**Comment by Qarj** [comment]
yes it is valid JSON but this project currently only supports JSON objects

As a workaround, just add your own key outside your array, put it through this project, then remove the key afterwards, for example:

```json
{
    "myArray": [
        { "name": "weather_forecast", "arguments": { "location": "New York" } },
        { "name": "currency_calculator", "arguments": { "base_amount": 123.45, "base_currency": "EUR", "quote_currency": "USD" } }
    ]
}
```

**Comment by marklysze** [comment]
Thanks @Qarj, I'll give that a go!

**Comment by marklysze** [comment]
Worked a treat, appreciated.
